// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `bookmark` table.
    ///
    /// (Automatically generated by Diesel.)
    bookmark (id) {
        /// The `id` column of the `bookmark` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `snippet` column of the `bookmark` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        snippet -> Text,
        /// The `source_id` column of the `bookmark` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        source_id -> Integer,
        /// The `created_at` column of the `bookmark` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Text,
    }
}

diesel::table! {
    /// Representation of the `kanji` table.
    ///
    /// (Automatically generated by Diesel.)
    kanji (id) {
        /// The `id` column of the `kanji` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `created_at` column of the `kanji` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Text,
        /// The `updated_at` column of the `kanji` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Text,
    }
}

diesel::table! {
    /// Representation of the `quiz_answer` table.
    ///
    /// (Automatically generated by Diesel.)
    quiz_answer (id) {
        /// The `id` column of the `quiz_answer` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `question` column of the `quiz_answer` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        question -> Text,
        /// The `answer` column of the `quiz_answer` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        answer -> Text,
        /// The `created_at` column of the `quiz_answer` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Text,
        /// The `source_id` column of the `quiz_answer` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        source_id -> Nullable<Integer>,
    }
}

diesel::table! {
    /// Representation of the `source` table.
    ///
    /// (Automatically generated by Diesel.)
    source (id) {
        /// The `id` column of the `source` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `path` column of the `source` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        path -> Text,
        /// The `name` column of the `source` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `created_at` column of the `source` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Text,
        /// The `updated_at` column of the `source` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Text,
        /// The `enabled` column of the `source` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        enabled -> Bool,
        /// The `weight` column of the `source` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        weight -> Integer,
    }
}

diesel::joinable!(bookmark -> source (source_id));
diesel::joinable!(quiz_answer -> source (source_id));

diesel::allow_tables_to_appear_in_same_query!(bookmark, kanji, quiz_answer, source,);
