CREATE TABLE IF NOT EXISTS quiz_answer (
  id TEXT NOT NULL PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  duration INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (question) REFERENCES kanji (id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (answer) REFERENCES kanji (id) ON DELETE CASCADE ON UPDATE CASCADE
)
