CREATE TABLE IF NOT EXISTS bookmark (
  id INTEGER NOT NULL PRIMARY KEY,
  snippet TEXT NOT NULL UNIQUE,
  source_id INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (source_id) REFERENCES source (id) ON DELETE CASCADE ON UPDATE CASCADE
)
